library(readcsv)
EPI_data <- read.csv("Box/Documents/MSBA/6962 Data Analytics/EPI_data.csv")
plot(ecdf(EPI_data$EPI),do.points=FALSE,verticals = TRUE) 
plot(ecdf(EPI_data$EPI),do.points=TRUE,verticals = TRUE)
par(pty='s')
qqnorm(EPI_data$EPI)
qqline(EPI_data$EPI)
x<-seq(30,95,1)
x
x2<-seq(30,95,2)
x3<-seq(30,96,3)
qqplot(qt(ppoints(250),df=5),x,xlab="Q-Q plot")
qqline(x)

plot(ecdf(EPI_data$DALY),do.points=FALSE,verticals = TRUE) 
plot(ecdf(EPI_data$DALY),do.points=TRUE,verticals = TRUE)
par(pty='s')
qqnorm(EPI_data$DALY)
qqline(EPI_data$DALY)
qqplot(qt(ppoints(250),df=5),EPI_data$DALY,xlab="Q-Q plot DALY")

plot(ecdf(EPI_data$WATER_H),do.points=FALSE,verticals = TRUE) 
plot(ecdf(EPI_data$WATER_H),do.points=TRUE,verticals = TRUE)
par(pty='s')
qqnorm(EPI_data$WATER_H)
qqline(EPI_data$WATER_H)

boxplot(EPI_data$EPI,EPI_data$DALY)
boxplot(EPI_data$EPI,EPI_data$ENVHEALTH)
boxplot(EPI_data$DALY,EPI_data$ECOSYSTEM)
boxplot(EPI_data$AIR_H,EPI_data$WATER_H)
boxplot(EPI_data$AIR_E,EPI_data$WATER_E)

multivariate <- read.csv("Box/Documents/MSBA/6962 Data Analytics/multivariate.csv")
View(multivariate)
attach(multivariate)
mm<-lm(multivariate$Homeowners~multivariate$Immigrant)
mm
plot(multivariate$Homeowners~multivariate$Immigrant)
abline(mm)
abline(mm,col=2,lwd=3)
attributes(mm)
mm$coefficients
